"""Neural network inference for ptychography (PtychoViT TensorRT)."""
from .inference import PtychoViTInference
from .orientation import (
    OrientationCandidate,
    OrientationReport,
    OrientationResult,
    autodetect_orientation,
)
from .preprocess import (
    D4_NAMES,
    D4_TRANSFORMS,
    apply_d4,
    apply_intensity_floor,
    auto_detect_roi_offsets,
    compute_intensity_normalization,
    compute_sample_pixel_size,
    crop_to_roi,
    detect_dc_at_corner,
    estimate_roi,
    fourier_shift,
    inner_crop_from_probe,
    inpaint_bad_pixels,
    mask_hot_pixels,
    mask_hot_pixels_by_count,
    normalize_intensity,
    preprocess_diffraction,
    remap_positions,
    resize_diffraction_patterns,
    spatially_diverse_sample,
    zero_pad_to_target,
)
from .stitch import (
    normalize_mosaic,
    place_patches_fourier_shift,
    stitch_batch_into,
    stitch_batch_livestitch_into,
    stitch_batch_nearest,
)
from .trt import (
    build_engine_from_onnx as build_engine,
    load_engine,
    save_engine,
)

__all__ = [
    "D4_NAMES",
    "D4_TRANSFORMS",
    "OrientationCandidate",
    "OrientationReport",
    "OrientationResult",
    "PtychoViTInference",
    "autodetect_orientation",
    "apply_d4",
    "apply_intensity_floor",
    "auto_detect_roi_offsets",
    "build_engine",
    "compute_intensity_normalization",
    "compute_sample_pixel_size",
    "crop_to_roi",
    "detect_dc_at_corner",
    "estimate_roi",
    "fourier_shift",
    "inner_crop_from_probe",
    "inpaint_bad_pixels",
    "load_engine",
    "mask_hot_pixels",
    "mask_hot_pixels_by_count",
    "normalize_intensity",
    "normalize_mosaic",
    "place_patches_fourier_shift",
    "preprocess_diffraction",
    "remap_positions",
    "resize_diffraction_patterns",
    "save_engine",
    "spatially_diverse_sample",
    "stitch_batch_into",
    "stitch_batch_livestitch_into",
    "stitch_batch_nearest",
    "zero_pad_to_target",
]
